### ISSUE TITLE
Please, reduce the numer of provided options required

### ISSUE THREAD

**Issue by Anton-Latukha** [chrisdone/hsmv#2]
Haskell has hierarchical module names hardcoded to the directory structure. At the very least so far - I did not found any counter-statement, as also not found a way to circumvent the system. So module names and directory tree are hardcoded. And are fully isomorphic.

The 2-3 times belaboring the same information defeats the half of the purpose of the program. Is there is dozens of modules to move - one needs to write a wrapper around the program to automate the module movement, and it is not easy because the program requests the information input in several forms at the same time.

---

It is enough information to provide one of the `{MODULEPATH, --from, --from-path}` and one of `{--to, --to-path}` not all at the same time.

**Comment by chrisdone** [comment]
![Screenshot from 2020-12-29 09-44-44](https://user-images.githubusercontent.com/11019/103274709-33660200-49ba-11eb-8ecc-46f724696457.png)

There's a fork button at the top right. Use it.
